# Porta HTTP padrão
server:
  port: ${SERVER_PORT:8092}
# ------------------------------------
# Configuração base da aplicação
# ------------------------------------

spring:
  # Nome da aplicação, pode ser sobrescrito via env VAR
  application:
    name: ${SPRING_APP_NAME:spring-event-service}

  # Perfil padrão (quando SPRING_PROFILES_ACTIVE não estiver definido)
  profiles:
    default: local

  # Desabilita Spring Cloud Config por padrão
  cloud:
    config:
      enabled: false

  # Configurações JPA comuns
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    properties:
      hibernate:
        format_sql: true    # formata SQL no console
    open-in-view: false    # evita manutenção de sessão aberta

  flyway:
    # migrações Flyway local
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ticketdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

# Configuração de documentação

springdoc:
  api-docs:
    path: /event/api-docs
  swagger-ui:
    path: /event/swagger-ui.html
  default-produces-media-type: application/json
# Endpoints de management (health, metrics, etc.)

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,refresh,bus-refresh
  tracing:
    sampling:
      probability: 1.0      # amostragem 100% para tracing
# Padrões de log e níveis comuns

logging:
  pattern:
    correlation: '%X{traceId:-} %X{spanId:-}'
    level: '%-5level [${spring.application.name}]'
  include-application-name: true
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot: WARN
    org.springframework.security: INFO
    io.opentelemetry: INFO
    io.micrometer: INFO
# Configurações OpenTelemetry

otel:
  instrumentation:
    jdbc:
      enabled: false        # desabilita instrumentação JDBC
  logs:
    exporter: none         # desabilita exportação de logs
  metrics:
    exporter: none         # desabilita exportação de métricas
# Versão da aplicação

app:
  contact:
    email: lsilva.info@gmail.com
  name: Event Service
  title: "Serviço de cadastro de Eventos"
  version: @project.version@
