spring:
  config:
    activate:
      on-profile: local

  datasource:
    # Banco MySQL local
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ticketdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: update
#  flyway:
#    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak local
          issuer-uri: http://${KEYCLOAK_URL:localhost}:8443/realms/event-management
          jwk-set-uri: http://${KEYCLOAK_URL:localhost}:8443/realms/event-management/protocol/openid-connect/certs

  keycloak:
    admin:
      client-id: ${KEYCLOAK_CLIENT_ID:user-service-admin}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:dev-secret}
      auth-server-url: http://${KEYCLOAK_URL:localhost}:8443
      realm: ${KEYCLOAK_REALM:event-management}

  rabbitmq:
    # RabbitMQ local
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    connection-timeout: 5  # timeout em segundos

loki:
  # Loki local (opcional)
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
  jobName: ${LOKI_JOB_NAME:spring-event-service}